image: debian

before_script:
  - apt update -qq
  - apt install -y -qq python3-pip python3-dev python3-pyqt5 python3-pyqt5.qtsvg python3-matplotlib python3-numpy python3-pytest

stages:
  - test
  - release
  - deploy

test_debian_testing:
  image: debian:testing
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
  - mkdir -p /tmp/runtime-pyspreadci
  - export XDG_RUNTIME_DIR=/tmp/runtime-pyspreadci
  - py.test-3

test_debian_unstable:
  image: debian:unstable
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
  - mkdir -p /tmp/runtime-pyspreadci
  - export XDG_RUNTIME_DIR=/tmp/runtime-pyspreadci
  - py.test-3

test_debian_experimental:
  image: debian:experimental
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
  - mkdir -p /tmp/runtime-pyspreadci
  - export XDG_RUNTIME_DIR=/tmp/runtime-pyspreadci
  - py.test-3


## Release to pypi
deploy_pypi:
  stage: release
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - echo "$TWINE_USERNAME"
    - pip3 install twine
    - python3 setup.py sdist bdist_wheel
    #- python3 -m twine upload dist/*
    - python3 -m twine upload --verbose --repository-url https://test.pypi.org/legacy/ dist/*
  only:
    - tags



## api.docs pages at pyspread.gitlab.io/pyspread
pages:
  stage: deploy
  image: debian:experimental
  script:
  - apt install -y -qq python3-sphinx
  - pip3 install -r apidocs/requirements.txt
  - mkdir public
  - sphinx-build -a -b html ./apidocs ./public/
  artifacts:
    paths:
    - public
  only:
  - master

